=== SD-PS2017/30434-a3-OnaciuAndreea/MedicalSoft/src/main/resources/db/Book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Book" xmlns:tns="http://www.example.org/Book" elementFormDefault="qualified">

    <element name="Book" type="tns:book"></element>

    <complexType name="NewType"></complexType>

    <complexType name="book">
    	<sequence>
    		<element name="title" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="genre" type="tns:Genre" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="additionalInformation" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="quantity" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="price" type="float" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="Genre">
    	<sequence>
    		<element name="type" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== SD-PS2017/30434-a3-OnaciuAndreea/MedicalSoft/src/main/resources/db/Book.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Book xmlns:tns="http://www.example.org/Book" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Book Book.xsd ">
  <tns:title>Ion</tns:title>
  <tns:author>Liviu Rebreanu</tns:author>
  <tns:genre>
    <tns:type>fiction</tns:type>
  </tns:genre>
  <tns:additionalInformation></tns:additionalInformation>
  <tns:quantity>50</tns:quantity>
  <tns:price>12.3</tns:price>
</tns:Book>
